name: Build and Test Docker UI

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t sample:latest ./pipeline

      - name: Run Docker container
        run: docker run -d -p 8080:80 sample:latest

      - name: Test HTML
        run: curl http://localhost:8080
