name: Build and Test Docker UI

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Docker login using secrets
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build Docker image from your folder
      - name: Build Docker image
        run: docker build -t my-ui:latest ./my-ui

      # 4. Run Docker container inside GitHub VM
      - name: Run Docker container
        run: docker run -d -p 8080:80 my-ui:latest

      # 5. Test if HTML page is served
      - name: Test HTML
        run: curl http://localhost:8080
